---
title: "01_data_processing"
author: "Margaret Janiczek"
date: "2025-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```


# Load data
```{r}
load(here::here("data/golub_exprs_pheno.Rdata"))

dat_raw <- golub.exprs.pheno
```


# Do initial explorations

```{r}
# make a table of demographic/clinical variables

clin_dat <- dat_raw %>%  select(Samples:cancer)

# pivot to long format

gene_dat <- dat_raw %>%
  pivot_longer(-c(Samples:cancer), names_to = "genes") %>%
  group_by(genes)

# calculate standard deviation, mean, and coef variance
gene_var <- gene_dat %>%
  group_by(genes) %>%
  summarise(sd = sd(value),
            mean = mean(value),
            coef_var = sd/mean) %>%
  arrange(sd)

# make an index for the top 20% of variable genes
gene_index <- gene_var %>%
  ungroup() %>%
  slice_head(n = round(.2*length(gene_var$genes),0))


# select for genes in the top variable 
analysis_dat <- gene_dat %>%
  filter(genes %in% gene_index$genes) %>%
  group_by(genes) %>%
  mutate(scaled_value = scale(value))


# if you want data back in wide format
analysis_dat_wide <- analysis_dat %>%
  select(-value) %>%
  pivot_wider(names_from = genes, values_from = scaled_value)


```


# Do any transformations/modifications

```{r}
# for example consider standardizing each gene

summary(golub.exprs.pheno[,6:20])

#create gene.matrix, trimmed version of Golub dataset
gene_matrix = as.matrix(dat_raw[,-(1:6)])


hist(gene_matrix[,5])

hist(gene_matrix[,100])
```

# Save data to use in analysis
